import { PaymentMethod, PaymentStatus, SubscriptionStatus, UserPlan } from '@prisma/client';
import prisma from '../config/database';
import logger from '../config/logger';
// Atualizado para novo sistema de planos: mensal, trimestral, anual

const PLAN_PERIOD: Record<UserPlan, number> = {
  mensal: 1,
  trimestral: 3,
  anual: 12,
};

const DAY_IN_MS = 24 * 60 * 60 * 1000;

interface BillingStats {
  lastCycleRanAt: Date | null;
  lastCycleDurationMs: number | null;
  invoicesCreated: number;
  accountsSuspended: number;
}

const stats: BillingStats = {
  lastCycleRanAt: null,
  lastCycleDurationMs: null,
  invoicesCreated: 0,
  accountsSuspended: 0,
};

const getGraceDays = () => Math.max(Number(process.env.BILLING_GRACE_DAYS) || 5, 1);

const addMonths = (date: Date, months: number) => {
  const result = new Date(date);
  result.setMonth(result.getMonth() + months);
  return result;
};

const resolveDueDate = (subscription: { startDate: Date; endDate: Date | null; plan: UserPlan }) => {
  if (subscription.endDate) return new Date(subscription.endDate);
  const period = PLAN_PERIOD[subscription.plan] || 1;
  return addMonths(subscription.startDate, period);
};

export async function generatePendingInvoices(now: Date = new Date()): Promise<number> {
  const graceDays = getGraceDays();
  const subs = await prisma.subscription.findMany({
    where: {
      status: { in: [SubscriptionStatus.active, SubscriptionStatus.trial] },
      // Removido filtro 'not free' - todos os planos agora são pagos
      autoRenew: true,
      isRecurring: true,
    },
    select: {
      id: true,
      userId: true,
      plan: true,
      amount: true,
      startDate: true,
      endDate: true,
      autoRenew: true,
    },
  });

  let created = 0;

  for (const subscription of subs) {
    const dueDate = resolveDueDate(subscription);
    if (dueDate > now) continue;

    const existingPending = await prisma.payment.findFirst({
      where: {
        subscriptionId: subscription.id,
        status: PaymentStatus.pending,
        createdAt: { gte: new Date(dueDate.getTime() - DAY_IN_MS) },
      },
    });
    if (existingPending) continue;

    await prisma.payment.create({
      data: {
        userId: subscription.userId,
        subscriptionId: subscription.id,
        amount: subscription.amount,
        currency: 'BRL',
        status: PaymentStatus.pending,
        paymentMethod: PaymentMethod.credit_card,
        description: `Renovação automática (${subscription.plan})`,
        metadata: JSON.stringify({
          autoGenerated: true,
          dueDate: dueDate.toISOString(),
        }),
        expiresAt: new Date(dueDate.getTime() + graceDays * DAY_IN_MS),
      },
    });

    created += 1;
  }

  if (created > 0) {
    logger.info('Billing: cobranças pendentes geradas', { count: created });
  }

  return created;
}

export async function suspendDelinquentAccounts(now: Date = new Date()): Promise<number> {
  const graceDays = getGraceDays();
  const subscriptions = await prisma.subscription.findMany({
    where: {
      status: { in: [SubscriptionStatus.active, SubscriptionStatus.trial] },
      // Removido filtro 'not free' - todos os planos agora são pagos
      autoRenew: true,
      isRecurring: true,
    },
    select: {
      id: true,
      userId: true,
      plan: true,
      status: true,
      startDate: true,
      endDate: true,
    },
  });

  let suspended = 0;

  for (const subscription of subscriptions) {
    const dueDate = resolveDueDate(subscription);
    const graceLimit = new Date(dueDate.getTime() + graceDays * DAY_IN_MS);
    if (graceLimit >= now) continue;

    const paidInvoice = await prisma.payment.findFirst({
      where: {
        subscriptionId: subscription.id,
        status: PaymentStatus.paid,
        paidAt: { gte: dueDate },
      },
    });
    if (paidInvoice) continue;

    await prisma.subscription.update({
      where: { id: subscription.id },
      data: {
        status: SubscriptionStatus.suspended,
        autoRenew: false,
        cancelledAt: now,
        metadata: JSON.stringify({
          reason: 'Pagamento não identificado após período de tolerância',
          suspendedAt: now.toISOString(),
        }),
      },
    });

    await prisma.user.update({
      where: { id: subscription.userId },
      data: {
        plan: 'mensal', // Rebaixar para plano mais básico
        isActive: false,
      },
    });

    suspended += 1;
  }

  if (suspended > 0) {
    logger.warn('Billing: contas suspensas por inadimplência', { count: suspended });
  }

  return suspended;
}

export async function getBillingHealth() {
  const now = new Date();
  const pending = await prisma.payment.count({
    where: {
      status: PaymentStatus.pending,
      createdAt: { gte: new Date(now.getTime() - 30 * DAY_IN_MS) },
    },
  });
  const overdue = await prisma.payment.count({
    where: {
      status: PaymentStatus.pending,
      expiresAt: { lt: now },
    },
  });
  const activeSubs = await prisma.subscription.count({
    where: {
      status: SubscriptionStatus.active,
      // Removido filtro 'not free' - todos os planos agora são pagos
    },
  });

  return {
    pendingInvoices: pending,
    overdueInvoices: overdue,
    activeSubscriptions: activeSubs,
    gracePeriodDays: getGraceDays(),
    lastCycleRanAt: stats.lastCycleRanAt,
    lastCycleDurationMs: stats.lastCycleDurationMs,
    invoicesCreated: stats.invoicesCreated,
    accountsSuspended: stats.accountsSuspended,
  };
}

export async function runBillingCycle(now: Date = new Date()) {
  const start = Date.now();
  const invoices = await generatePendingInvoices(now);
  const suspensions = await suspendDelinquentAccounts(now);

  stats.lastCycleRanAt = new Date();
  stats.lastCycleDurationMs = Date.now() - start;
  stats.invoicesCreated = invoices;
  stats.accountsSuspended = suspensions;

  logger.info('Billing cycle finalizado', {
    invoices,
    suspensions,
    durationMs: stats.lastCycleDurationMs,
  });
}

let monitorHandle: NodeJS.Timeout | null = null;

export function startBillingMonitor() {
  if (process.env.DISABLE_BILLING_MONITOR === 'true') {
    logger.warn('Billing monitor desabilitado via DISABLE_BILLING_MONITOR');
    return;
  }

  if (monitorHandle) return;

  const intervalMs = Number(process.env.BILLING_MONITOR_INTERVAL_MS) || 15 * 60 * 1000;

  const execute = async () => {
    try {
      await runBillingCycle();
    } catch (error) {
      logger.error('Erro ao executar ciclo de billing', {
        error: error instanceof Error ? error.message : String(error),
      });
    }
  };

  execute();
  monitorHandle = setInterval(execute, intervalMs);
  logger.info('Billing monitor iniciado', { intervalMs });
}

export function stopBillingMonitor() {
  if (monitorHandle) {
    clearInterval(monitorHandle);
    monitorHandle = null;
    logger.info('Billing monitor parado');
  }
}

